#!/usr/bin/env bash
# Copyright (C) 2020, Robin Vobruba <hoijui.quaero@gmail.com>
# Licensed under the GPL v3, see LICENSE-GPLv3.md.
#
# Runs pre-processing, and then jekyll *build* (or *serve*).

# Exit immediately on each error and unset variable;
# see: https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/
#set -Eeuo pipefail
set -Eeu

script_dir=$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")
tools_dir=$(cd "$script_dir/.."; pwd)
project_dir=$(pwd)
data_dir="$project_dir/_data"

action="${1:-build}"

if [ "$action" != "build" ] && [ "$action" != "serve" ]
then
	>&2 echo "WARNING: First parameter ('action') needs to be either 'build' or 'serve', was '$action'!"
	exit 1
fi

"$script_dir/pre-process"

cd "$project_dir"

bundle exec jekyll "$action"
